# app.yaml for Nexus Singularity repository
# Created for lordturtle96 on 2025-08-11

runtime: nodejs16
service: nexus-singularity
instance_class: F2

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.65

env_variables:
  PORT: 8080
  NODE_ENV: production
  PROJECT_NAME: "Nexus Singularity"
  CREATED_BY: "lordturtle96"

inbound_services:
  - warmup
