name: Super-Linter

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Super-Linter
        uses: super-linter/super-linter@v7.4.0
