name: Accessibility Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: browser-actions/setup-chrome@latest
      - name: Install dependencies
        run:sudo npm install -g http-server pa11y-ci
          npm install -g http-server pa11y-ci
      - name: Start server
        run: |
          http-server -p 8080 &
          sleep 5
      - name: Run accessibility tests
        run: |
          pa11y-ci http://localhost:8080/index.html http://localhost:8080/crucible-exchange.html http://localhost:8080/proclamation-pillar.html
